name: eslint check
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn eslint:check
